version: '3.6'
services:
  redis:
    image: ragedunicorn/redis:1.0.5-stable
    volumes:
      - redis_data:/data
    secrets:
        - com.ragedunicorn.redis.app_password
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.redis.environment: "prod"
      com.ragedunicorn.redis.description: "Redis container"
volumes:
  redis_data: {}
secrets:
  com.ragedunicorn.redis.app_password:
    external: true
