version: '3.4'
services:
  redis:
    build: .
    image: ragedunicorn/redis:1.0.2-stable
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      com.ragedunicorn.redis.environment: "prod"
      com.ragedunicorn.redis.description: "Redis container"
volumes:
  redis_data: {}
