version: '3.6'
services:
  redis:
    build: .
    image: ragedunicorn/redis:${REDIS_TAG_VERSION}-dev
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.redis.environment: "dev"
      com.ragedunicorn.redis.description: "Redis container"
volumes:
  redis_data: {}
