version: '3.6'
services:
  redis:
    build: .
    image: ragedunicorn/redis:${REDIS_TAG_VERSION}-stable
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.redis.environment: "prod"
      com.ragedunicorn.redis.description: "Redis container"
volumes:
  redis_data: {}
