version: '3.3'
services:
  redis:
    build: .
    image: ragedunicorn/redis:1.0.0-stable
    volumes:
      - redis_data:/data
    expose:
      - "6379"
    secrets:
        - com.ragedunicorn.redis.password
    labels:
      com.ragedunicorn.redis.environment: "prod"
      com.ragedunicorn.redis.description: "Redis container"
volumes:
  redis_data: {}
secrets:
  com.ragedunicorn.redis.password:
    external: true
